//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternettClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://main", ConfigurationName="ServiceReference1.ServicePortType")]
    public interface ServicePortType {
        
        // CODEGEN: Parameter 'Username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Authenticate", ReplyAction="urn:AuthenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InternettClient.ServiceReference1.AuthenticateResponse Authenticate(InternettClient.ServiceReference1.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Authenticate", ReplyAction="urn:AuthenticateResponse")]
        System.Threading.Tasks.Task<InternettClient.ServiceReference1.AuthenticateResponse> AuthenticateAsync(InternettClient.ServiceReference1.AuthenticateRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReturnString", ReplyAction="urn:ReturnStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InternettClient.ServiceReference1.ReturnStringResponse ReturnString(InternettClient.ServiceReference1.ReturnStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReturnString", ReplyAction="urn:ReturnStringResponse")]
        System.Threading.Tasks.Task<InternettClient.ServiceReference1.ReturnStringResponse> ReturnStringAsync(InternettClient.ServiceReference1.ReturnStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://main", IsWrapped=true)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://main", IsWrapped=true)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main", Order=0)]
        public bool @return;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnString", WrapperNamespace="http://main", IsWrapped=true)]
    public partial class ReturnStringRequest {
        
        public ReturnStringRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnStringResponse", WrapperNamespace="http://main", IsWrapped=true)]
    public partial class ReturnStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ReturnStringResponse() {
        }
        
        public ReturnStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicePortTypeChannel : InternettClient.ServiceReference1.ServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePortTypeClient : System.ServiceModel.ClientBase<InternettClient.ServiceReference1.ServicePortType>, InternettClient.ServiceReference1.ServicePortType {
        
        public ServicePortTypeClient() {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InternettClient.ServiceReference1.AuthenticateResponse InternettClient.ServiceReference1.ServicePortType.Authenticate(InternettClient.ServiceReference1.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string Username, string Password) {
            InternettClient.ServiceReference1.AuthenticateRequest inValue = new InternettClient.ServiceReference1.AuthenticateRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            InternettClient.ServiceReference1.AuthenticateResponse retVal = ((InternettClient.ServiceReference1.ServicePortType)(this)).Authenticate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InternettClient.ServiceReference1.AuthenticateResponse> InternettClient.ServiceReference1.ServicePortType.AuthenticateAsync(InternettClient.ServiceReference1.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<InternettClient.ServiceReference1.AuthenticateResponse> AuthenticateAsync(string Username, string Password) {
            InternettClient.ServiceReference1.AuthenticateRequest inValue = new InternettClient.ServiceReference1.AuthenticateRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            return ((InternettClient.ServiceReference1.ServicePortType)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InternettClient.ServiceReference1.ReturnStringResponse InternettClient.ServiceReference1.ServicePortType.ReturnString(InternettClient.ServiceReference1.ReturnStringRequest request) {
            return base.Channel.ReturnString(request);
        }
        
        public string ReturnString() {
            InternettClient.ServiceReference1.ReturnStringRequest inValue = new InternettClient.ServiceReference1.ReturnStringRequest();
            InternettClient.ServiceReference1.ReturnStringResponse retVal = ((InternettClient.ServiceReference1.ServicePortType)(this)).ReturnString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InternettClient.ServiceReference1.ReturnStringResponse> InternettClient.ServiceReference1.ServicePortType.ReturnStringAsync(InternettClient.ServiceReference1.ReturnStringRequest request) {
            return base.Channel.ReturnStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<InternettClient.ServiceReference1.ReturnStringResponse> ReturnStringAsync() {
            InternettClient.ServiceReference1.ReturnStringRequest inValue = new InternettClient.ServiceReference1.ReturnStringRequest();
            return ((InternettClient.ServiceReference1.ServicePortType)(this)).ReturnStringAsync(inValue);
        }
    }
}
